In [0]:
#Question 1
import numpy as np

In [46]:
#Question 2
np.version.version

'1.16.5'

In [0]:
#Question 3
arr = np.zeros(10)

In [48]:
#Question 4 
print(arr.size)

10


5.) by using question mark after writting the command


In [49]:
#Question 6
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [50]:
#Question 7
b  = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [51]:
#Question 8
b = np.flip(b,0)
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [52]:
#Question 9
c = np.arange(9).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [53]:
#Question 10
d = np.where([1,2,0,0,4,0])
print(d)

(array([0, 1, 4]),)


In [54]:
#Question 11
e = np.identity(3,dtype="int")
print(e)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [55]:
#Question 12
np.random.rand(27).reshape(3,3,3)

array([[[0.62905795, 0.20589162, 0.54785805],
        [0.45606115, 0.54367811, 0.55806932],
        [0.44653718, 0.70146801, 0.59075843]],

       [[0.31512163, 0.44240296, 0.65624787],
        [0.79806268, 0.26439945, 0.83443895],
        [0.36116923, 0.14899891, 0.82231906]],

       [[0.03773057, 0.69962851, 0.68212642],
        [0.01243435, 0.44855728, 0.93872829],
        [0.19700527, 0.17427126, 0.08457761]]])

In [56]:
#Question 13
f = np.random.rand(100).reshape(10,10)
print(f)
print(np.max(f))
print(np.min(f))

[[0.11589115 0.82140806 0.59209088 0.77641325 0.03335695 0.69152251
  0.3836049  0.64553434 0.4105805  0.00725744]
 [0.26536438 0.69905207 0.81143524 0.35301564 0.43011422 0.66429835
  0.11152199 0.31585792 0.29747852 0.00138903]
 [0.72899045 0.52527789 0.1771192  0.49305584 0.92192287 0.31441248
  0.23107872 0.45773215 0.953343   0.68782503]
 [0.05933919 0.74086948 0.48638978 0.04670179 0.41061416 0.72522588
  0.58954797 0.78365062 0.10250746 0.52677665]
 [0.01823057 0.54787658 0.40252971 0.56097485 0.36456    0.44913494
  0.69857905 0.64423387 0.43649778 0.53751406]
 [0.51941332 0.55433438 0.92739477 0.88582667 0.65351175 0.10461371
  0.70176073 0.38654953 0.99413197 0.78889802]
 [0.91425531 0.48368124 0.29471146 0.35142969 0.69270683 0.19540908
  0.02779225 0.43280698 0.2566414  0.65324272]
 [0.15938061 0.99609432 0.98354533 0.69673942 0.27868305 0.16242749
  0.52884774 0.0301354  0.97814318 0.48020215]
 [0.65808003 0.04762312 0.99985999 0.05664755 0.04278185 0.95584574
  0.20362679

In [57]:
#Question 14
print(np.mean(np.random.rand(30),0))

0.47749974852810706


In [58]:
#Question 15
g = np.ones((10,10))
g[1:-1,1:-1] = 0
print(g)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [59]:
#Question 16
h = np.ones((3,3))
h = np.pad(h,pad_width=1,mode="constant",constant_values=0)
print(h)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [60]:
#Question 17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [61]:
#Question 18
i = np.arange(4)
i = i+1
i = np.diag(i,k=-1)
print(i)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [62]:
#Question 19
j = np.zeros((8,8))
j[::2,::2]=1
j[1::2,1::2]=1
print(j)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [63]:
#Question 20
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [64]:
#Question 21
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [65]:
#Question 22
k = np.random.random((3,3))
kmin , kmax = np.min(k) , np.max(k)
print(k)
print((k-kmin)/(kmax - kmin))
kmean , kstd = np.mean(k) , np.std(k)
print((k - kmean)/kstd)

[[0.43253963 0.83772037 0.96965634]
 [0.28859057 0.61738815 0.15681118]
 [0.87468792 0.11148771 0.18241063]]
[[0.37411286 0.84625869 1.        ]
 [0.20637304 0.58951169 0.05281418]
 [0.88933595 0.         0.0826445 ]]
[[-0.20239563  1.07356484  1.48904626]
 [-0.65570763  0.37971349 -1.070696  ]
 [ 1.18997987 -1.21342479 -0.99008041]]


In [68]:
#Question 23
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])      
print(color)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [69]:
#Question 24 
print(np.dot(np.arange(15).reshape(5,3),np.arange(6).reshape(3,2)))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [70]:
#Question 25 
l = np.arange(15)
l[(l>3) & (l<8)] *= -1
print(l)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


In [72]:
#Question 26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

TypeError: ignored

In [73]:
#Question 27
Z = np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<<Z>>Z)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]
[0 1 2 3 4]


In [74]:
#Question 28
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [75]:
#Question 29
array1 = np.array([1,2,4,5,6,7,8])
array2 = np.array([2,3,4,7,8])
print(np.intersect1d(array1,array2))

[2 4 7 8]


In [79]:
#Question 32
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [80]:
#Question 33
print("Yesterday", np.datetime64('today','D') - np.timedelta64(1,'D'))
print("Today", np.datetime64('today','D'))
print("Tomorrow", np.datetime64('today','D') + np.timedelta64(1,'D'))


Yesterday 2019-10-13
Today 2019-10-14
Tomorrow 2019-10-15


In [81]:
#Question 34
m = np.arange('2017-07','2017-08',dtype='datetime64[D]')
print(m)

['2017-07-01' '2017-07-02' '2017-07-03' '2017-07-04' '2017-07-05'
 '2017-07-06' '2017-07-07' '2017-07-08' '2017-07-09' '2017-07-10'
 '2017-07-11' '2017-07-12' '2017-07-13' '2017-07-14' '2017-07-15'
 '2017-07-16' '2017-07-17' '2017-07-18' '2017-07-19' '2017-07-20'
 '2017-07-21' '2017-07-22' '2017-07-23' '2017-07-24' '2017-07-25'
 '2017-07-26' '2017-07-27' '2017-07-28' '2017-07-29' '2017-07-30'
 '2017-07-31']


In [82]:
#Question 35
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.divide(A,B,out=A)

array([-0.16666667, -0.16666667, -0.16666667])

In [86]:
#Question 36
n = np.random.uniform(0,10,10)
print(n)

print(n - n%1)
print(np.floor(n))
print(n.astype(int))
print(np.ceil(n)-1)
print(np.trunc(n))

[4.94788809 0.37202656 1.51653078 0.05176849 4.74245033 9.97003092
 9.11132444 3.10553641 2.53149621 2.4181235 ]
[4. 0. 1. 0. 4. 9. 9. 3. 2. 2.]
[4. 0. 1. 0. 4. 9. 9. 3. 2. 2.]
[4 0 1 0 4 9 9 3 2 2]
[4. 0. 1. 0. 4. 9. 9. 3. 2. 2.]
[4. 0. 1. 0. 4. 9. 9. 3. 2. 2.]


In [87]:
#Question 37
o = np.zeros((5,5))
o += np.arange(5)
print(o)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [88]:
#Question 38
p = np.linspace(0,1,11,endpoint=False)[1:]
print(p)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [91]:
#Question 40
q = np.random.random(10)
q = np.sort(q)
print(q)

[0.12213068 0.14192559 0.18070741 0.25132862 0.31210958 0.38641511
 0.55668504 0.87828916 0.88350831 0.91360114]


In [92]:
#Question 41
r = np.arange(10)
print(np.add.reduce(r))

45


In [93]:
#Question 42
A = np.random.random(10).reshape(5,2)
B = np.random.random(10).reshape(5,2)

print(np.array_equal(A,B))

False


In [0]:
#Question 43
s = np.zeros(3)
s.flags.writeable = False

In [95]:
#Question 44
t = np.random.random((10,2))
X,Y = t[:,0],t[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.85449242 0.96578907 0.59648482 1.30963224 1.33370174 0.62353987
 1.07472372 0.52353385 1.08638349 1.31535219]
[1.42551861 1.46152676 0.3281328  0.75519363 0.77488752 0.83079704
 1.12547075 0.08739942 0.83923536 0.84459455]


In [96]:
#Question 45
u = np.random.random(10)
u[np.argmax(u)]=0
print(u)

[0.76764917 0.48979615 0.36514155 0.70054053 0.84507165 0.95068714
 0.24484422 0.         0.54846483 0.113288  ]


In [97]:
#Question 46
v = np.zeros((5,5), [('x',float),('y',float)])
v['x'], v['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(v)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [99]:
#Question 49
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [100]:
#Question 47
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [101]:
#Question 48
for dtype in [np.int8, np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max,"\n")

for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max,"\n")

-128
127 

-2147483648
2147483647 

-9223372036854775808
9223372036854775807 

-3.4028235e+38
3.4028235e+38 

-1.7976931348623157e+308
1.7976931348623157e+308 



In [102]:
#Question 50
w = np.arange(100)
val = np.random.uniform(0,100)
index = (np.abs(w-val)).argmin()
print(w[index])

27


In [103]:
#Question 51
print(np.zeros(10,[ ('position', [('x',float,1),('y',float,1)]),
                    ('color' , [('r',float,1),('g',float,1),('b',float,1)])]))

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [104]:
#Question 52

x = np.random.random((10,2))
X,Y = np.atleast_2d(x[:,0], x[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D,"\n")
import scipy
import scipy.spatial
x = np.random.random((10,2))
D = scipy.spatial.distance.cdist(x,x)

print(D)

[[0.         0.68648268 0.7535493  0.17028233 0.53838756 0.3857237
  0.42337881 0.40540396 0.60683727 0.3345622 ]
 [0.68648268 0.         0.60204448 0.6768602  0.27268995 0.96958811
  0.39406014 0.82636649 0.19194733 0.69903861]
 [0.7535493  0.60204448 0.         0.87037975 0.76923071 0.77202825
  0.80269059 0.55280592 0.73846691 0.4885005 ]
 [0.17028233 0.6768602  0.87037975 0.         0.47059302 0.5431641
  0.33444303 0.57513276 0.55396881 0.4963675 ]
 [0.53838756 0.27268995 0.76923071 0.47059302 0.         0.89120895
  0.14131474 0.80594242 0.09195558 0.68066986]
 [0.3857237  0.96958811 0.77202825 0.5431641  0.89120895 0.
  0.79527176 0.22093726 0.94318434 0.30263816]
 [0.42337881 0.39406014 0.80269059 0.33444303 0.14131474 0.79527176
  0.         0.73995898 0.23156768 0.62183095]
 [0.40540396 0.82636649 0.55280592 0.57513276 0.80594242 0.22093726
  0.73995898 0.         0.83922275 0.12855324]
 [0.60683727 0.19194733 0.73846691 0.55396881 0.09195558 0.94318434
  0.23156768 0.8392227

In [105]:
#Question 53
y = np.arange(10,dtype=np.float32)
print(y)
y = y.astype(np.int32,copy=False)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


In [106]:
#Question 54
from io import StringIO

# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [107]:
#Question 55
z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
    print(index, value)
for index in np.ndindex(z.shape):
    print(index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [108]:
#Question 56
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [109]:
#Question 57
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [110]:
#Question 58
x = np.random.random((5,10))

x = x - x.mean(axis=1,keepdims=True)
print(x)

[[-0.11114705 -0.19735432  0.25984879 -0.01368105  0.21275396 -0.18667139
   0.25671698 -0.13005859 -0.20034345  0.10993612]
 [-0.24099267 -0.10893098 -0.56329635  0.31799932  0.18773239  0.40941247
   0.08515895 -0.40894623 -0.08391541  0.40577851]
 [ 0.42811517  0.06700334  0.18007851 -0.03915899  0.1562178   0.12953999
   0.05160426 -0.42993177 -0.35498879 -0.18847951]
 [ 0.29130436  0.15263725  0.11934487 -0.01308646 -0.45006617 -0.11620508
  -0.39370788 -0.03484949  0.18813086  0.25649776]
 [ 0.2250792   0.35229065 -0.03344866  0.31707285  0.11748461 -0.16910129
  -0.32433333 -0.14747022  0.06602328 -0.40359708]]


In [111]:
#Question 59
a = np.random.randint(0,12,(4,3))
print(a)
print(a[a[:,1].argsort()])

[[ 0  7  5]
 [10  0  4]
 [ 6  6 11]
 [ 6  0  8]]
[[10  0  4]
 [ 6  0  8]
 [ 6  6 11]
 [ 0  7  5]]


In [112]:
#Question 60
b = np.random.randint(0,3,(3,10))
print((~b.any(axis=0)).any())

False


In [113]:
#Question 61
c = np.random.uniform(0,1,10)
z = 0.5
m = c.flat[np.abs(c - z).argmin()]
print(m)

0.4896109363948091


In [114]:
#Question 62
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [115]:
#Question 63
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [116]:
#Question 64
d = np.ones(10)
I = np.random.randint(0,len(d),20)
d += np.bincount(I, minlength=len(d))
print(d)


[2. 2. 2. 5. 6. 2. 2. 3. 3. 3.]


In [117]:
#Question 65
e = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
f = np.bincount(I,e)
print(f)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [118]:
#Question 66
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [119]:
#Question 67
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[50 45 56 61]
 [44 67 55 64]
 [62 67 72 43]]
[[50 45 56 61]
 [44 67 55 64]
 [62 67 72 43]]


In [120]:
#Question 68
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.47458116 0.25331452 0.44365201 0.60276954 0.47452921 0.55772457
 0.50862139 0.50210328 0.57197122 0.41061372]
0    0.474581
1    0.253315
2    0.443652
3    0.602770
4    0.474529
5    0.557725
6    0.508621
7    0.502103
8    0.571971
9    0.410614
dtype: float64


In [121]:
#Question 69
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
  
np.diag(np.dot(A, B))

array([0.77650527, 1.7229372 , 2.11262369, 1.74780986, 0.74919112])

In [122]:
#Question 70
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [123]:
#Question 71
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [124]:
#Question 72
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [125]:
#Question 73
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 83) ( 2, 84) (13, 31) (13, 92) (20, 26) (22, 33) (22, 66) (26, 26)
 (29, 54) (29, 69) (31, 81) (31, 82) (31, 92) (33, 66) (38, 48) (38, 50)
 (44, 47) (44, 66) (44, 69) (44, 73) (47, 73) (48, 50) (50, 52) (50, 98)
 (52, 98) (54, 69) (66, 69) (81, 82) (83, 84)]


In [126]:
#Question 74
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [127]:
#Question 75
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [128]:
#Question 76
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [129]:
#Question 77
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.80311739, -0.78650935,  0.21641815,  0.84126567, -0.07164067,
        0.58749393, -0.08864386, -0.96189487,  0.95659285, -0.12452558,
        0.34199085,  0.31754199,  0.50436062,  0.90875843,  0.63758121,
       -0.21519501,  0.50969557, -0.38843526,  0.60297041, -0.58270857,
        0.34467995, -0.48006467, -0.78296148,  0.42986452,  0.61134724,
        0.20878102,  0.85750229,  0.32747292, -0.72376131,  0.15184202,
       -0.47770439,  0.45671118, -0.86074545,  0.07211125,  0.89513675,
       -0.95463567,  0.93951049,  0.36641252, -0.744626  ,  0.78372809,
       -0.93984506,  0.68031568, -0.76176455, -0.85150388,  0.28784237,
        0.31188413,  0.32885582, -0.06680336, -0.91065893,  0.66936208,
       -0.08678462, -0.34487999,  0.97618272,  0.89836969, -0.46173616,
        0.82520117,  0.18565449,  0.59218044, -0.92395793, -0.16108096,
        0.07041484, -0.97739099, -0.70939665, -0.56438381,  0.04608823,
        0.48416573, -0.5571103 , -0.9025389 ,  0.21451987, -0.49

In [130]:
#Question 78
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[11.50131217  3.61959891  0.83671731  0.14850842  1.35664338  6.95743981
  4.19687884  9.69877517  1.21526596  4.30157885]


In [131]:
#Question 79
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[12.07892231 12.67971458  4.10575459  2.61265703 13.69891278  3.68377805
   6.86458648  7.98326776  9.68100402  4.06695091]
 [ 7.10773637  7.43047846 12.689106   13.74241672  5.3217355   9.22709533
   4.43379196  3.05841669  1.09139866  5.98562358]
 [ 6.685356    7.38660941  0.51799328  2.02690528 10.03465372  2.21488922
   0.78831815  2.57350765  6.17399994  1.97380911]
 [ 0.26257331  0.70251794  7.17777005 13.32319178  0.53240419  2.04590776
   3.18976233  3.80559672  3.50828226  8.86776284]
 [ 3.01317057  3.63161598  1.57414768  6.3888005   5.50013023  1.75159175
   2.05561188  1.08471165  1.60075227  2.76526808]
 [15.76980255 16.45805698  1.85627838  1.90470642 18.31361753  3.09273464
   9.68679895 11.6594112  14.33871108  8.92291947]
 [ 9.13205396  9.81942723  0.48116405  1.29479641 12.12440088  0.47792171
   3.27368949  5.0223135   8.22296825  3.61792239]
 [ 0.87939064  0.11090201  4.45005008  3.52473304  3.90160811  8.30574956
   7.10397938  5.0017759   0.19048438  2.57646587]


In [134]:
#Question 81
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [135]:
#Question 82
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [136]:
#Question 83
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


In [137]:
#Question 84
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 0 0]
   [1 0 2]
   [1 2 3]]

  [[0 0 1]
   [0 2 4]
   [2 3 0]]

  [[0 1 1]
   [2 4 3]
   [3 0 1]]

  [[1 1 2]
   [4 3 0]
   [0 1 4]]

  [[1 2 0]
   [3 0 3]
   [1 4 3]]

  [[2 0 3]
   [0 3 3]
   [4 3 2]]

  [[0 3 0]
   [3 3 2]
   [3 2 0]]

  [[3 0 3]
   [3 2 4]
   [2 0 4]]]


 [[[1 0 2]
   [1 2 3]
   [1 2 4]]

  [[0 2 4]
   [2 3 0]
   [2 4 4]]

  [[2 4 3]
   [3 0 1]
   [4 4 4]]

  [[4 3 0]
   [0 1 4]
   [4 4 2]]

  [[3 0 3]
   [1 4 3]
   [4 2 2]]

  [[0 3 3]
   [4 3 2]
   [2 2 4]]

  [[3 3 2]
   [3 2 0]
   [2 4 3]]

  [[3 2 4]
   [2 0 4]
   [4 3 1]]]


 [[[1 2 3]
   [1 2 4]
   [0 2 1]]

  [[2 3 0]
   [2 4 4]
   [2 1 0]]

  [[3 0 1]
   [4 4 4]
   [1 0 3]]

  [[0 1 4]
   [4 4 2]
   [0 3 2]]

  [[1 4 3]
   [4 2 2]
   [3 2 4]]

  [[4 3 2]
   [2 2 4]
   [2 4 3]]

  [[3 2 0]
   [2 4 3]
   [4 3 0]]

  [[2 0 4]
   [4 3 1]
   [3 0 1]]]


 [[[1 2 4]
   [0 2 1]
   [0 1 2]]

  [[2 4 4]
   [2 1 0]
   [1 2 4]]

  [[4 4 4]
   [1 0 3]
   [2 4 4]]

  [[4 4 2]
   [0 3 2]
   [4 4 1]]

  [[4 2 2]
   

In [138]:
#Question 85
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7  8 11  3 13]
 [ 8  1 15 10  1]
 [11 15  7 42  9]
 [ 3 10 42  8  4]
 [13  1  9  4  8]]


In [139]:
#Question 86
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [140]:
#Question 87
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [141]:
#Question 88
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [142]:
#Question 89
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [143]:
#Question 90
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [144]:
#Question 91
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [145]:
#Question 92
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 3: 3.68 s per loop
10 loops, best of 3: 165 ms per loop
10 loops, best of 3: 150 ms per loop


In [146]:
#Question 93
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 4 6 7]


In [147]:
#Question 94
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[1 1 3]
 [0 4 2]
 [4 3 2]
 [4 1 3]
 [0 0 4]
 [4 0 2]
 [4 0 3]
 [0 1 4]
 [4 2 2]
 [0 0 2]]
[[1 1 3]
 [0 4 2]
 [4 3 2]
 [4 1 3]
 [0 0 4]
 [4 0 2]
 [4 0 3]
 [0 1 4]
 [4 2 2]
 [0 0 2]]


In [148]:
#Question 95
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [149]:
#Question 97

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B) 

array([[5.57561688e-01, 1.63396355e-01, 4.90883542e-01, 1.35457579e-01,
        1.27793758e-01, 1.28788443e-03, 1.53682804e-01, 2.88247004e-01,
        4.59949879e-01, 3.89137269e-01],
       [3.89323604e-01, 1.14093309e-01, 3.42764853e-01, 9.45847501e-02,
        8.92334026e-02, 8.99279519e-04, 1.07310715e-01, 2.01271653e-01,
        3.21165081e-01, 2.71719395e-01],
       [5.59812391e-01, 1.64055935e-01, 4.92865087e-01, 1.36004379e-01,
        1.28309622e-01, 1.29308322e-03, 1.54303174e-01, 2.89410567e-01,
        4.61806554e-01, 3.90708096e-01],
       [3.75852372e-01, 1.10145494e-01, 3.30904630e-01, 9.13119635e-02,
        8.61457813e-02, 8.68162981e-04, 1.03597589e-01, 1.94307325e-01,
        3.10052245e-01, 2.62317460e-01],
       [1.62882541e-01, 4.77335764e-02, 1.43403609e-01, 3.95717193e-02,
        3.73328593e-02, 3.76234400e-04, 4.48959212e-02, 8.42066543e-02,
        1.34366845e-01, 1.13680098e-01],
       [4.18116565e-01, 1.22531236e-01, 3.68114497e-01, 1.01579895e-01,
   

In [0]:
#Question 98
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [151]:
#Question 99
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [152]:
#Question 100
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.39604777 -0.00292491]
