In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [33]:
xdf = pd.read_csv('./data/Logistic_X_Train.csv')
ydf = pd.read_csv('./data/Logistic_Y_Train.csv')
xtest = pd.read_csv('./data/Logistic_X_Test.csv')

x = xdf.values
y = ydf.values
xtest = xtest.values
print(xtest)

[[-0.76750773 -0.2618595  -2.51483147]
 [-1.24165258  1.44900144 -0.4130893 ]
 [ 1.92527007  1.93176097  1.34261917]
 ...
 [-1.18696873  0.94734729 -0.78638597]
 [-0.53232395  1.84516978 -0.9935503 ]
 [ 0.54023217  0.58099406  0.38664901]]


In [0]:
# define hypothesis

def hypothesis(x,w,b):
  hx = np.dot(x,w)+b
  return sigmoid(hx)

def sigmoid(z):
  return 1/(1 + np.exp(-1*z))

In [0]:
#define error function

def error(x,y,w,b):
  m = x.shape[0]

  for i in range(m):
    hx = hypothesis(x[i],w,b)
    err += y[i]* np.log2(hx) + (1-y[i])*log2(1-hx)

  return err/m

In [0]:
#define gradient

def gradient(x,y,w,b):
  gb =0.0
  gw = np.zeros(w.shape)
  m = x.shape[0]

  for i in range(m):
    hx = hypothesis(x[i],w,b)
    gb += (y[i] - hx)*x[i]
    gw += (y[i] -hx)

  return [gw/m,gb/m]

In [0]:
#define main gradient decent

def gradient_decent(x,y,w,b,lr=0.01):
  err = error(x,y,w,b)
  [gradw , gradb] = gradient(x,y,w,b)
  w += gradw*lr
  b += gradb*lr

  return e,w,b

In [0]:

def predict(x,w,b):
  confidence = hypothesis(x,w,b)
  if confidence < 0.5:
    return 0
  else: 
    return 1

In [39]:

arr = []
m = xtest.shape[0]
w = 2*np.random.random((xtest.shape[1]),)
b = 5*np.random.random()

for i in range(m):
   arr.append(predict(xtest[i],w,b))

predicated = np.array(arr)
print(predicated)



[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 